### Import the relevant libraries

The simplest most flexible way to work with matrices in python is by using arrays

In [1]:
import numpy as np

### Declaring scalars, vectors, and matrices

#### Scalars

In [2]:
s = 5

In [3]:
s

5

#### Vectors

In [4]:
v = np.array([5,-2,4]) 

In [5]:
v # by default, v is a row vector

array([ 5, -2,  4])

#### Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

#### Data types

In [9]:
type(s)

int

In [10]:
type(v) # 1-dimensional, ndarray = n-dimensional array

numpy.ndarray

In [11]:
type(m) # 2-dimensional

numpy.ndarray

In [12]:
s_array = np.array(5)
s_array

array(5)

In [13]:
type(s_array)

numpy.ndarray

#### Data shapes

returns the shape (dimensions) of a variable

In [14]:
m.shape

(2, 3)

In [15]:
v.shape

(3,)

#### Creating a column vector

In [16]:
v.reshape(1,3) # gives an array a new shape, without changing its data

array([[ 5, -2,  4]])

In [17]:
v.reshape(3,1) # column vector

array([[ 5],
       [-2],
       [ 4]])

In [18]:
s_array.shape # 0-dimensional object

()