### Import the relevant libraries

In [7]:
import numpy as np

### Addition

#### Addition of scalars

In [8]:
5 + 5

10

In [9]:
10 - 4

6

#### Addition of matrices

In [10]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1 # 2x3

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [11]:
m2 = np.array([[5,3],[-2,4]])
m2 # 2x2

array([[ 5,  3],
       [-2,  4]])

In [12]:
m1 + m2

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### Addition of vectors

In [13]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [14]:
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

In [15]:
v1 + v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

#### Exceptions (addition with a scalar)

mathematically these operations are not allowed, due to the shape is different, but in Python, it works.

This result has a meaning in terms of arrays, but not in terms of linear algebra

In [16]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [17]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [18]:
v1

array([1, 2, 3, 4, 5])

In [19]:
v1 + 1

array([2, 3, 4, 5, 6])

In [20]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [21]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])