#### Import relevant libraries

In [14]:
import numpy as np

#### Dot product

In [15]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [16]:
np.dot(x,y)

-66

In [17]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [18]:
np.dot(u,v)

18

#### Scalar * Scalar

In [19]:
np.dot(5,6)

30

In [20]:
np.dot(10,-2)

-20

#### Scalar * Vector

In [21]:
x

array([ 2,  8, -4])

In [22]:
5*x # we get a vector with the same length, and its elements multiplied

array([ 10,  40, -20])

### Part 2

#### Scalar * Matrix

In [23]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [24]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

#### Matrix by matrix

In [25]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [27]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])